### ISSUE TITLE
New probe differences

### ISSUE THREAD

**Issue by goran-mahovlic** [dezanche/H-field_RF_probe#2]
Hi, 
first I want to than you for creating this probe!

I have some project with EMI/EMC testing in progress so I will do compare of few open probes and some closed and fancy available in stores. 

I have ordered your probes last year, before v2 so I wanted to ask if there is big differences with those two?

I also made simple push in case for the probe I can do pull request if you want to include it in repo or test it. 
It is bit bigger so it covers logos, but for me it is good enough...

![IMG_20240119_124853](https://github.com/dezanche/H-field_RF_probe/assets/4248736/9c7a0a0a-8be2-4e55-84ce-ae8bc9c8864e)

Best,
Goran

**Comment by dezanche** [comment]
Hi,
I'm glad you find this probe useful.
The only difference between v1 and v2 is the area covered by the ground planes. You can see the difference in the photos in the readme. There shouldn't be any difference in sensitivity to H fields at the loop but I did not perform a calibration. 
Your comparison could be useful if you publish it.
I'd like to try that cool case so go ahead and create the pull request or you can email me the file directly.
Thanks,
nick

**Comment by goran-mahovlic** [comment]
> Hi, I'm glad you find this probe useful. The only difference between v1 and v2 is the area covered by the ground planes. You can see the difference in the photos in the readme. There shouldn't be any difference in sensitivity to H fields at the loop but I did not perform a calibration. Your comparison could be useful if you publish it. I'd like to try that cool case so go ahead and create the pull request or you can email me the file directly. Thanks, nick

Tnx! 

Here is the latest one.

https://github.com/goran-mahovlic/H-field_RF_probe/blob/main/Case/Probe_holder.stl

I am printing it like this: 

![Screenshot from 2024-01-23 09-57-43](https://github.com/dezanche/H-field_RF_probe/assets/4248736/d8e8730b-e743-4e9a-85df-53a49d77dba7)

And then just push probe inside as it it tight fit...

I first had version with screws but then I need screws, so for me this is cheaper and good enough option :)

**Comment by dezanche** [comment]
I found it didn't fit the SMA connector I had on mine so we printed a modified version.
Are you using this case for safety or just ergonomics?

**Comment by goran-mahovlic** [comment]
Oh, yes my was really tight fit. 

For ergonomics and just in case I do not introduce something by touching the active part of the probe

I am working with low voltage only so I am not concerned for safety...

**Comment by goran-mahovlic** [comment]
@dezanche I can also do this easier

![IMG_20240202_210623](https://github.com/dezanche/H-field_RF_probe/assets/4248736/c414032c-3d42-4c03-9a14-2222ad17b329)

I have used some ooen source camera holder and drilled holes for probe.

![IMG_20240202_210702](https://github.com/dezanche/H-field_RF_probe/assets/4248736/93a9b1ae-8c10-4e8e-86b4-9fe9a74aa601)

I need to create some holder for amplifier before working on some code that will move probe...

Will report you about progress...

**Comment by goran-mahovlic** [comment]
I have run the 10 minute probe test with your probe, one bought from aliexpress and TekBox one

Someone already compared TekBox with even expensive ones.

https://www.edn.com/review-tekbox-near-field-probes/ 

My scans are run without any amplifier as older version of ULX3S is good source of emissions.

Green is your probe, Yellow is TekBox one

![Screenshot from 2024-02-05 15-06-28](https://github.com/dezanche/H-field_RF_probe/assets/4248736/eee52628-f2f4-4301-a469-05e72dbfd565)

All 3 on one place - red is one I bought from Ali

![Screenshot from 2024-02-05 15-04-57](https://github.com/dezanche/H-field_RF_probe/assets/4248736/c0856dcd-6dc6-4f53-ab09-e138f9a76e9b)

And here is CSV for all 3 if you would like to investigate more.

[trace_data.csv](https://github.com/dezanche/H-field_RF_probe/files/14166752/trace_data.csv)

If you thing we can do something even better let me know.

**Comment by goran-mahovlic** [comment]
I will close this issue - my blog post is here 

https://intergalaktik.eu/news/bb3-cm4-emc

If you have any suggestions please let me know.

**Comment by dezanche** [comment]
Sorry I haven't replied recently. I checked out in your blog: the nice work!
(BTW a couple of the github links are broken)
Thanks for suggesting the case. I will post the modified version that fits the SMA connector I have on my probe
nick

**Comment by goran-mahovlic** [comment]
Tnx! 

Oh, I did not notice that links are broken but seams underline makes problem with URLs - fixed that now with creating short links for URL.

Cool for the case!
